---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve(retrieve)
	analyze_images(analyze_images)
	generate(generate)
	judge_gate(judge_gate)
	correct(correct)
	abstain(abstain)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve;
	analyze_images --> generate;
	correct --> generate;
	generate --> judge_gate;
	judge_gate -. &nbsp;accept&nbsp; .-> __end__;
	judge_gate -.-> abstain;
	judge_gate -.-> correct;
	retrieve -.-> analyze_images;
	retrieve -.-> generate;
	abstain --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
